--USER TABLE
INSERT INTO USERS (USERNAME, PASSWORD, ROLE, NAME, STATE, ZIP_CODE, PEANUT_ALLERGIES, EGG_ALLERGIES, DAIRY_ALLERGIES)
VALUES ('admin', '$2a$12$dNv6zMoESTtouE1RSU6B1uebwxMH2ZfZnyTnWKs8TzgxOoJN4wbnm', 'ROLE_ADMIN', 'Admin John', 'Victoria', '1111', false, false, false); --password = 1234

INSERT INTO USERS (USERNAME, PASSWORD, ROLE, NAME, STATE, ZIP_CODE, PEANUT_ALLERGIES, EGG_ALLERGIES, DAIRY_ALLERGIES)
VALUES ('operator', '$2a$12$dNv6zMoESTtouE1RSU6B1uebwxMH2ZfZnyTnWKs8TzgxOoJN4wbnm', 'ROLE_OPERATOR', 'Operator Duke', 'NSW', '2222', false, false, false); --password = 1234

--RESTAURANT TABLE
INSERT INTO RESTAURANTS (NAME, ZIP_CODE, PEANUT_SCORE, EGG_SCORE, DAIRY_SCORE, OVERALL_SCORE)
VALUES ('NOM MA', 1010, null, null, null, null);

INSERT INTO RESTAURANTS (NAME, ZIP_CODE, PEANUT_SCORE, EGG_SCORE, DAIRY_SCORE, OVERALL_SCORE)
VALUES ('MC DONALD', 1011, null, null, null, null);

INSERT INTO RESTAURANTS (NAME, ZIP_CODE, PEANUT_SCORE, EGG_SCORE, DAIRY_SCORE, OVERALL_SCORE)
VALUES ('KFC', 1012, null, null, null, null);

INSERT INTO RESTAURANTS (NAME, ZIP_CODE, PEANUT_SCORE, EGG_SCORE, DAIRY_SCORE, OVERALL_SCORE)
VALUES ('BABABOO', 1012, null, null, null, null);